In [42]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import svm

In [43]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [44]:
df_features = pd.read_csv('/content/drive/MyDrive/bank_transaction_features.csv')

In [45]:
df_features


bank_transaction_id         bank_transaction_description  \
0                 21786195                             citylink   
1                 21786196                             citylink   
2                 21786197                        1Jul19 OYSTER   
3                 21786198                           travelodge   
4                 21786199                        6Jul19 RINGGO   
...                    ...                                  ...   
12495             24140325                            COVERSURE   
12496             24140326   DIRECTLINE INS FASTER PAYMENTS OUT   
12497             24140327  SUNDRY DEBIT Direct Debit coversure   
12498             24140328       17Aug19 insurance Direct Debit   
12499             24140329             enterprise car insurance   

       bank_transaction_amount bank_transaction_type  
0                       -13.80                   MPO  
1                       -13.14                   DEB  
2                       -36.98                   DEB  
3                       -75.73                   MPO  
4                       -37.86                   CSH  
...                        ...                   ...  
12495                   -28.46                   FPO  
12496                   -35.64                   FPO  
12497                   -22.37                    DD  
12498                   -23.11                    DD  
12499                   -24.15                    DD  

[12500 rows x 4 columns]

In [46]:
df_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12500 entries, 0 to 12499
Data columns (total 4 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   bank_transaction_id           12500 non-null  int64  
 1   bank_transaction_description  12369 non-null  object 
 2   bank_transaction_amount       12500 non-null  float64
 3   bank_transaction_type         12500 non-null  object 
dtypes: float64(1), int64(1), object(2)
memory usage: 390.8+ KB


In [47]:
df_features.describe()

bank_transaction_id  bank_transaction_amount
count         1.250000e+04             12500.000000
mean          2.226077e+07               -19.613017
std           9.391952e+05                15.060147
min           2.178620e+07              -102.590000
25%           2.178932e+07               -28.022500
50%           2.179244e+07               -19.040000
75%           2.179557e+07                -4.687500
max           2.414033e+07                -0.320000

In [48]:
df_features.isnull().sum()

bank_transaction_id               0
bank_transaction_description    131
bank_transaction_amount           0
bank_transaction_type             0
dtype: int64

In [49]:
#df_new = df_features.dropna()

In [50]:
#df_new.isnull().sum()

In [51]:
df_1 = df_features.groupby('bank_transaction_type').nunique()

In [52]:
df_1

bank_transaction_id  bank_transaction_description  \
bank_transaction_type                                                      
CHG                                   2510                          1543   
CSH                                   2041                          1686   
DD                                    1108                           926   
DEB                                   4678                          3899   
FPO                                    679                           618   
MPO                                   1484                          1370   

                       bank_transaction_amount  
bank_transaction_type                           
CHG                                        211  
CSH                                       1619  
DD                                         827  
DEB                                       3013  
FPO                                        577  
MPO                                       1260

In [67]:
df_description = df_features['bank_transaction_description']

In [68]:
df_description

0                                   citylink
1                                   citylink
2                              1Jul19 OYSTER
3                                 travelodge
4                              6Jul19 RINGGO
                        ...                 
12495                              COVERSURE
12496     DIRECTLINE INS FASTER PAYMENTS OUT
12497    SUNDRY DEBIT Direct Debit coversure
12498         17Aug19 insurance Direct Debit
12499               enterprise car insurance
Name: bank_transaction_description, Length: 12500, dtype: object

In [69]:
df_description.str.lower()

0                                   citylink
1                                   citylink
2                              1jul19 oyster
3                                 travelodge
4                              6jul19 ringgo
                        ...                 
12495                              coversure
12496     directline ins faster payments out
12497    sundry debit direct debit coversure
12498         17aug19 insurance direct debit
12499               enterprise car insurance
Name: bank_transaction_description, Length: 12500, dtype: object

In [70]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [71]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

In [72]:
pattern = '[0-9]'

In [73]:
import re

In [74]:
df_description = df_description.str.replace(r'[^a-zA-Z ]\s?',r'',regex=True)

In [75]:
df_description

0                                   citylink
1                                   citylink
2                                  JulOYSTER
3                                 travelodge
4                                  JulRINGGO
                        ...                 
12495                              COVERSURE
12496     DIRECTLINE INS FASTER PAYMENTS OUT
12497    SUNDRY DEBIT Direct Debit coversure
12498              Auginsurance Direct Debit
12499               enterprise car insurance
Name: bank_transaction_description, Length: 12500, dtype: object

In [76]:
df_description =df_description.astype(str)

In [77]:
df_description

0                                   citylink
1                                   citylink
2                                  JulOYSTER
3                                 travelodge
4                                  JulRINGGO
                        ...                 
12495                              COVERSURE
12496     DIRECTLINE INS FASTER PAYMENTS OUT
12497    SUNDRY DEBIT Direct Debit coversure
12498              Auginsurance Direct Debit
12499               enterprise car insurance
Name: bank_transaction_description, Length: 12500, dtype: object

In [78]:
from sklearn.feature_extraction.text import CountVectorizer

In [79]:
vectorizer = CountVectorizer()

In [80]:
vectorizer

CountVectorizer()

In [81]:
vectorizer.fit(df_description)

CountVectorizer()

In [82]:
X = vectorizer.transform(df_description)
print(X)

  (0, 162)	1
  (1, 162)	1
  (2, 648)	1
  (3, 815)	1
  (4, 652)	1
  (5, 148)	1
  (5, 167)	1
  (5, 176)	1
  (5, 740)	1
  (5, 794)	1
  (6, 790)	1
  (7, 809)	1
  (8, 11)	1
  (8, 155)	1
  (8, 417)	1
  (8, 705)	1
  (8, 811)	1
  (8, 819)	1
  (9, 739)	1
  (10, 167)	1
  (10, 736)	1
  (10, 815)	1
  (11, 398)	1
  (12, 12)	1
  (12, 787)	1
  :	:
  (12492, 593)	1
  (12493, 176)	1
  (12493, 348)	1
  (12493, 349)	1
  (12493, 372)	1
  (12493, 580)	1
  (12494, 98)	1
  (12494, 176)	1
  (12494, 348)	1
  (12495, 171)	1
  (12496, 349)	1
  (12496, 369)	1
  (12496, 580)	1
  (12496, 738)	1
  (12496, 743)	1
  (12497, 171)	1
  (12497, 176)	2
  (12497, 348)	1
  (12497, 794)	1
  (12498, 63)	1
  (12498, 176)	1
  (12498, 348)	1
  (12499, 149)	1
  (12499, 363)	1
  (12499, 581)	1


In [128]:
X.shape

(12500, 845)

In [129]:
x_train = X[:10001]

In [130]:
y_train = X[10002:]

In [131]:
from sklearn.preprocessing import LabelEncoder

In [132]:
le = LabelEncoder()

In [133]:
X_T = le.fit_transform(x_test)

In [134]:
X_T

array([4, 4, 4, ..., 2, 2, 4])

In [135]:
Y_T = le.fit_transform(y_test)

In [136]:
Y_T

array([4, 4, 4, ..., 2, 2, 2])

In [137]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix

In [138]:
model = SVC()

In [139]:
model.fit(x_train,X_T)

SVC()

In [140]:
predict = model.predict(x_train)

In [141]:
print(accuracy_score(X_T,predict)*100)

94.5005499450055


In [142]:
CM_train = confusion_matrix(X_T, predict)
CM_train

array([[2887,    0,    0,    4,  126],
       [   0, 2248,    0,    0,    2],
       [   1,    0,  880,   21,   18],
       [  82,   11,   41, 1043,   58],
       [  64,   45,    0,   77, 2393]])

In [143]:
predict_test = model.predict(y_train)

In [144]:
print(accuracy_score(Y_T,predict_test)*100)

91.79343474779824


In [145]:
Precision= precision_score(Y_T, predict_test,  average="macro")
Precision

0.9154020895158649

In [146]:
Recall = recall_score(Y_T, predict_test,  average="macro")
Recall

0.9128406736169836

In [147]:
F1 = f1_score(Y_T, predict_test,  average="macro")
F1

0.9137805337127063

In [148]:
CM_test = confusion_matrix(Y_T, predict_test)

In [149]:
CM_test

array([[707,   1,   0,   0,  40],
       [  1, 536,   0,   0,   3],
       [  1,   2, 234,   3,  10],
       [ 19,   1,  21, 308,  25],
       [ 29,  15,   0,  34, 508]])

In [150]:

from sklearn.linear_model import LogisticRegression 
classifier = LogisticRegression(random_state = 0) 
classifier.fit(x_train, X_T) 


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [151]:

y_pred = classifier.predict(x_train) 


In [152]:
print(accuracy_score(X_T,y_pred)*100)

93.84061593840616


In [153]:
predict_logistic = classifier.predict(y_train)

In [154]:
print(accuracy_score(Y_T,predict_logistic)*100)

91.67333867093676


In [155]:
Precision= precision_score(Y_T, predict_logistic,  average="macro")

In [156]:
Precision

0.9131480319531837

In [157]:
Recall = recall_score(Y_T, predict_logistic,  average="macro")
Recall

0.91173455197089

In [158]:
F1 = f1_score(Y_T, predict_logistic,  average="macro")

In [159]:
F1

0.9117713254664093

In [160]:
CM_logistic = confusion_matrix(Y_T, predict_logistic)

In [161]:
CM_logistic

array([[706,   4,   0,   0,  38],
       [  0, 539,   0,   0,   1],
       [  0,   6, 236,   5,   3],
       [ 18,   3,  22, 302,  29],
       [ 26,  22,   0,  31, 507]])

In [162]:
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import LSTM, Dense, Embedding
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences

# Load the dataset
data = pd.read_csv('/content/drive/MyDrive/bank_transaction_features.csv')
print(data.head(10))


   bank_transaction_id             bank_transaction_description  \
0             21786195                                 citylink   
1             21786196                                 citylink   
2             21786197                            1Jul19 OYSTER   
3             21786198                               travelodge   
4             21786199                            6Jul19 RINGGO   
5             21786200  SUNDRY DEBIT CONTACTLESS CAMDEN PARKING   
6             21786201                                 stgcoach   
7             21786202                                trainline   
8             21786203        Fin: CMT UK LTD  Cash at Transact   
9             21786204                                   OYSTER   

   bank_transaction_amount bank_transaction_type  
0                   -13.80                   MPO  
1                   -13.14                   DEB  
2                   -36.98                   DEB  
3                   -75.73                   MPO  
4      

In [163]:
# Prepare input features
descriptions = data['bank_transaction_description'].values
amounts = data['bank_transaction_amount'].values
types = data['bank_transaction_type'].values
transaction_ids = data['bank_transaction_id'].values


In [164]:
descriptions = descriptions.astype(str)
tokenizer = Tokenizer()
max_sequence_length = max(len(sequence) for sequence in descriptions)

In [165]:
# # Tokenize and pad transaction descriptions
# tokenizer = Tokenizer()
# tokenizer.fit_on_texts(descriptions)
# descriptions = tokenizer.texts_to_sequences(descriptions)
# max_sequence_length = max(len(sequence) for sequence in descriptions)
# descriptions = pad_sequences(descriptions, maxlen=max_sequence_length)

In [166]:



# # Normalize amounts
# amounts = (amounts - amounts.min()) / (amounts.max() - amounts.min())

# # Convert transaction types to one-hot encoding
# types = pd.get_dummies(types)

# # Split the data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(
#     descriptions, transaction_ids, test_size=0.2, random_state=42)

# # Build the LSTM model
# model = Sequential()
# model.add(Embedding(len(tokenizer.word_index) + 1, 100, input_length=max_sequence_length))
# model.add(LSTM(100))
# model.add(Dense(1, activation='linear'))

# # Compile and train the model
# model.compile(loss='mse', optimizer='adam')
# model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=32)

# Make predictions on new data



In [167]:
# Example input data
# new_descriptions = ['Online payment', 'ATM withdrawal']
# new_amounts = [50.75, 100.0]
# new_types = ['Payment', 'Withdrawal']

# # Tokenize and pad the new descriptions
# new_descriptions = tokenizer.texts_to_sequences(new_descriptions)
# new_descriptions = pad_sequences(new_descriptions, maxlen=max_sequence_length)

# # Normalize the new amounts
# new_amounts = (new_amounts - amounts.min()) / (amounts.max() - amounts.min())

# # Convert the new types to one-hot encoding
# new_types = pd.get_dummies(new_types)

# # Make predictions
# predictions = model.predict([new_descriptions, new_amounts, new_types])




In [178]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/bank_transaction_features.csv')

# Preprocessing
X = df.drop('bank_transaction_id', axis=1)  # Input features
y = df['bank_transaction_id']  # Target variable

In [182]:
df.head(10)

bank_transaction_id             bank_transaction_description  \
0             21786195                                 citylink   
1             21786196                                 citylink   
2             21786197                            1Jul19 OYSTER   
3             21786198                               travelodge   
4             21786199                            6Jul19 RINGGO   
5             21786200  SUNDRY DEBIT CONTACTLESS CAMDEN PARKING   
6             21786201                                 stgcoach   
7             21786202                                trainline   
8             21786203        Fin: CMT UK LTD  Cash at Transact   
9             21786204                                   OYSTER   

   bank_transaction_amount bank_transaction_type  
0                   -13.80                   MPO  
1                   -13.14                   DEB  
2                   -36.98                   DEB  
3                   -75.73                   MPO  
4                   -37.86                   CSH  
5                   -34.79                   DEB  
6                    -7.26                   DEB  
7                   -26.71                   DEB  
8                   -36.25                   CSH  
9                   -21.80                   DEB

In [179]:

# Encode categorical variables
le = LabelEncoder()
X['bank_transaction_description'] = le.fit_transform(X['bank_transaction_description'])

X['bank_transaction_type'] = le.fit_transform(X['bank_transaction_type'])
print(X)

       bank_transaction_description  bank_transaction_amount  \
0                              8412                   -13.80   
1                              8412                   -13.14   
2                               209                   -36.98   
3                              9327                   -75.73   
4                               518                   -37.86   
...                             ...                      ...   
12495                          1404                   -28.46   
12496                          1582                   -35.64   
12497                          5781                   -22.37   
12498                           138                   -23.11   
12499                          8552                   -24.15   

       bank_transaction_type  
0                          5  
1                          3  
2                          3  
3                          5  
4                          1  
...                      ...  
12495         

In [180]:



# Scale numerical features
scaler = StandardScaler()
X['bank_transaction_amount'] = scaler.fit_transform(X['bank_transaction_amount'].values.reshape(-1, 1))

In [181]:
X

bank_transaction_description  bank_transaction_amount  \
0                              8412                 0.386002   
1                              8412                 0.429828   
2                               209                -1.153221   
3                              9327                -3.726340   
4                               518                -1.211656   
...                             ...                      ...   
12495                          1404                -0.587467   
12496                          1582                -1.064241   
12497                          5781                -0.183072   
12498                           138                -0.232210   
12499                          8552                -0.301270   

       bank_transaction_type  
0                          5  
1                          3  
2                          3  
3                          5  
4                          1  
...                      ...  
12495                      4  
12496                      4  
12497                      2  
12498                      2  
12499                      2  

[12500 rows x 3 columns]

In [169]:


# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the model architecture
model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dropout(0.2))
model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1, activation='linear'))

# Compile the model
model.compile(loss='mean_squared_error', optimizer=Adam(lr=0.001))

# Train the model
model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=50, batch_size=32)

# Predict transaction IDs
predictions = model.predict(X_val)

# Print some sample predictions
for i in range(5):
    print('Actual ID:', y_val.iloc[i], 'Predicted ID:', predictions[i][0])


Epoch 1/50
313/313 [==============================] - 2s 3ms/step - loss: 491798921216000.0000 - val_loss: 475348793819136.0000
Epoch 2/50
313/313 [==============================] - 1s 3ms/step - loss: 421311159468032.0000 - val_loss: 340297674391552.0000
Epoch 3/50
313/313 [==============================] - 1s 3ms/step - loss: 251937345765376.0000 - val_loss: 167881715220480.0000
Epoch 4/50
313/313 [==============================] - 1s 3ms/step - loss: 145876299284480.0000 - val_loss: 125231557509120.0000
Epoch 5/50
313/313 [==============================] - 1s 3ms/step - loss: 134078628102144.0000 - val_loss: 123794949668864.0000
Epoch 6/50
313/313 [==============================] - 1s 3ms/step - loss: 133366468837376.0000 - val_loss: 123727505260544.0000
Epoch 7/50
313/313 [==============================] - 1s 2ms/step - loss: 133431262445568.0000 - val_loss: 123767116267520.0000
Epoch 8/50
313/313 [==============================] - 1s 2ms/step - loss: 132632440471552.0000 - val_los

In [173]:
print(X_val)

       bank_transaction_description  bank_transaction_amount  \
1766                           1357                -0.871672   
11919                          6244                 1.091203   
8909                           8675                 1.162254   
4963                           6278                 0.358113   
10099                          5348                -0.944051   
...                             ...                      ...   
12493                          2121                -0.255451   
9296                           1720                -0.291973   
6085                           5710                 1.062649   
3883                           8008                -0.758787   
10372                          8661                -1.233569   

       bank_transaction_type  
1766                       3  
11919                      0  
8909                       0  
4963                       4  
10099                      5  
...                      ...  
12493         

In [184]:
# Create a new validation sample
new_val_sample = pd.DataFrame({
    'bank_transaction_description': ['travelodge'],
    'bank_transaction_type': ['MFO'],
    'bank_transaction_amount': [-75.73]
})

# Preprocess the new validation sample
le = LabelEncoder()
new_val_sample['bank_transaction_description'] = le.fit_transform(new_val_sample['bank_transaction_description'])
new_val_sample['bank_transaction_type'] = le.fit_transform(new_val_sample['bank_transaction_type'])

scaler = StandardScaler()
new_val_sample['bank_transaction_amount'] = scaler.fit_transform(new_val_sample['bank_transaction_amount'].values.reshape(-1, 1))

# Make predictions on the new validation sample
predictions = model.predict(new_val_sample)

# Print the predicted transaction ID
print('Predicted ID:', predictions[0][0])

1/1 [==============================] - 0s 22ms/step
Predicted ID: 37166.17


In [185]:
import pandas as pd
import numpy as np
data = pd.read_csv('/content/drive/MyDrive/bank_transaction_features.csv')
messages = []
labels = []
for index, row in data.iterrows():
    messages.append(row['Message'])
    if row['Category'] == 'ham':
        labels.append(0)
    else:
        labels.append(1)
messages = np.asarray(messages)
labels = np.asarray(labels)

KeyError: ignored